lang: en
timezone: AEDT/Australia
title: Everything web
tagline: Technical Specialist
description: >- 
  The ramblings of my adventures into all things technical, both from a personal and work life perspecitve. Expect everything from topics about Smart Home Automation and Home Labbing, to DevOps and AI (all personal interests) to more work related content around evertyhing Microsoft.

url: "https://osotechie.com"
github:
  username: gulianiDeepika.github.io 
social:
  name: O so techie
  links:
    - https://github.com/gulianiDeepika 
    - https://www.linkedin.com/in/deepikaguliani
